project_id = "isnhgyycowmnlxtmbmwm"

[functions.send-task-reminders]
verify_jwt = false

[functions.task-ai-helper]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.handle-task-action]
verify_jwt = false

[functions.get-notifications]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-daily-summary]
verify_jwt = false
